label_to_search_query = {
    '-': '',
    'beef carpaccio': 'carpaccio',
    'beet salad': 'beet',
    'breakfast burrito': 'burrito',
    'caesar salad': 'caesar salad',
    'caprese salad': 'caprese',
    'chicken quesadilla': 'quesadilla',
    'chicken wings': 'chicken',
    'clam chowder': 'chowder',
    'club sandwich': 'sandwich',
    'deviled eggs': 'egg',
    'dumplings': 'dumplings',
    'eggplant': 'eggplant',
    'falafel': 'falafel',
    'french fries': 'fries',
    'french toast': 'toast',
    'fried rice': 'fried rice',
    'gnocchi': 'gnocchi',
    'greek salad': 'salad',
    'guacamole': 'guacamole',
    'gyoza': 'dumplings',
    'hamburger': 'burger',
    'hot dog': 'hotdog',
    'hummus': 'hummus',
    'ice cream': 'ice cream',
    'lentil soup': 'lentil soup',
    'macaroni and cheese': 'mac and cheese',
    'molokhia': 'soup',
    'mussels': 'mussels',
    'nachos': 'nachos',
    'omelette': 'omelette',
    'onion rings': 'onion',
    'pancakes': 'pancakes',
    'samosa': 'samosa',
    'sashimi': 'sashimi',
    'spring rolls': 'rolls',
    'steak': 'steak',
    'stuffed grape leaves': 'stuffed',
    'sushi': 'sushi',
    'sweet potato': 'sweet potato',
    'tacos': 'tacos',
    'waffles': 'waffles'
}
